### ISSUE TITLE
SUPABASE_KEY in .env.example

### ISSUE THREAD

**Issue by pferreirafabricio** [luckyhackersacademy/onlygists#1]
Hi, I don't know if this was propositional but your `.env.example` has SUPABASE_KEY with a (valid?) token.

**Comment by leocastroz** [comment]
Possibly it may have gone unnoticed, but usually in `.env.example` it comes with empty "SUPABASE_URL" and "SUPABASE_KEY".

**Comment by IgorHalfeld** [comment]
É que não muita diferença aí, é só um arquivo de exemplo que mostra como serão as .envs
